/datum/voicepack/female
	preview = list("agony", "laugh", "pain", "hmph", "painmoan", "rage", "paincrit", "chuckle", "clearthroat", "embed", "grumble", "groan", "hmm", "huh", "laugh", "rage", "warcry")

/datum/voicepack/female/get_sound(soundin, modifiers)
	var/used
	switch(modifiers)
		if("old")
			used = getfold(soundin)
		if("young")
			used = getfyoung(soundin)
		if("silenced")
			used = getfsilenced(soundin)
	if(!used)
		switch(soundin)
			if("attack")
				used = list('sound/vo/female/gen/attack (1).ogg', 'sound/vo/female/gen/attack (2).ogg', 'sound/vo/female/gen/attack (3).ogg', 'sound/vo/female/gen/attack (4).ogg', 'sound/vo/female/gen/attack (5).ogg', 'sound/vo/female/gen/attack (6).ogg', 'sound/vo/female/gen/attack (7).ogg', 'sound/vo/female/gen/attack (8).ogg', 'sound/vo/female/gen/attack (9).ogg', 'sound/vo/female/gen/attack (10).ogg', 'sound/vo/female/gen/attack (11).ogg')
			if("deathgurgle")
				used = pick('sound/vo/female/gen/deathgurgle (1).ogg','sound/vo/female/gen/deathgurgle (2).ogg','sound/vo/female/gen/deathgurgle (3).ogg')
			if("agony")
				used = list('sound/vo/female/gen/agony (1).ogg','sound/vo/female/gen/agony (2).ogg','sound/vo/female/gen/agony (3).ogg')
			if("superagony") // to bypass painless override, use responsibly
				used = list('sound/vo/female/gen/agony (1).ogg','sound/vo/female/gen/agony (2).ogg','sound/vo/female/gen/agony (3).ogg')
			if("breathgasp")
				used = 'sound/vo/female/gen/breathgasp.ogg'
			if("burp")
				used = 'sound/vo/female/gen/burp.ogg'
			if("gulp")
				used = list('sound/vo/gulp.ogg', 'sound/vo/gulp2.ogg')
			if("sniff")
				used = list('sound/vo/sniff.ogg')
			if("salute")
				used = 'sound/vo/salute.ogg'
			if("crack")
				used = 'sound/vo/knuckles.ogg'
			if("facepalm")
				used = list('sound/vo/facepalm1.ogg', 'sound/vo/facepalm2.ogg')
			if("choke")
				used = list('sound/vo/female/gen/choke (1).ogg','sound/vo/female/gen/choke (2).ogg','sound/vo/female/gen/choke (3).ogg')
			if("chuckle")
				used = list('sound/vo/female/gen/chuckle (1).ogg','sound/vo/female/gen/chuckle (2).ogg','sound/vo/female/gen/chuckle (3).ogg')
			if("clearthroat")
				used = 'sound/vo/female/gen/clearthroat.ogg'
			if("cough")
				used = list('sound/vo/female/gen/cough (1).ogg','sound/vo/female/gen/cough (2).ogg')
			if("cry")
				used = list('sound/vo/female/gen/cry (1).ogg','sound/vo/female/gen/cry (2).ogg','sound/vo/female/gen/cry (3).ogg','sound/vo/female/gen/cry (4).ogg','sound/vo/female/gen/cry (5).ogg','sound/vo/female/gen/cry (6).ogg','sound/vo/female/gen/cry (7).ogg')
			if("drown")
				used = list('sound/vo/female/gen/drown (1).ogg','sound/vo/female/gen/drown (2).ogg','sound/vo/female/gen/drown (3).ogg')
			if("embed")
				used = list('sound/vo/female/gen/embed (1).ogg','sound/vo/female/gen/embed (2).ogg','sound/vo/female/gen/embed (3).ogg','sound/vo/female/gen/embed (4).ogg')
			if("fatigue")
				used = list('sound/vo/female/gen/fatigue (1).ogg','sound/vo/female/gen/fatigue (2).ogg','sound/vo/female/gen/fatigue (3).ogg')
			if("firescream")
				used = list('sound/vo/female/gen/firescream (1).ogg','sound/vo/female/gen/firescream (2).ogg')
			if("gag")
				used = list('sound/vo/female/gen/gag (1).ogg','sound/vo/female/gen/gag (2).ogg','sound/vo/female/gen/gag (3).ogg')
			if("gasp")
				used = list('sound/vo/female/gen/gasp (1).ogg','sound/vo/female/gen/gasp (2).ogg','sound/vo/female/gen/gasp (3).ogg')
			if("giggle")
				used = list('sound/vo/female/gen/giggle (1).ogg','sound/vo/female/gen/giggle (2).ogg')
			if("groan")
				used = list('sound/vo/female/gen/groan (1).ogg','sound/vo/female/gen/groan (2).ogg','sound/vo/female/gen/groan (3).ogg','sound/vo/female/gen/groan (4).ogg','sound/vo/female/gen/groan (5).ogg')
			if("grumble")
				used = 'sound/vo/female/gen/grumble.ogg'
			if("haltyell")
				used = list('sound/vo/female/gen/haltyell (1).ogg','sound/vo/female/gen/haltyell (2).ogg')
			if("hmm")
				used = 'sound/vo/female/gen/hmm.ogg'
			if("huh")
				used = list('sound/vo/female/gen/huh (1).ogg','sound/vo/female/gen/huh (2).ogg','sound/vo/female/gen/huh (3).ogg')
			if("hum")
				used = list('sound/vo/female/gen/hum (1).ogg','sound/vo/female/gen/hum (2).ogg','sound/vo/female/gen/hum (3).ogg')
			if("hmph")
				used = 'sound/vo/female/gen/hmph (1).ogg'
			if("jump")
				used = 'sound/vo/female/gen/jump.ogg'
			if("leap")
				used = 'sound/vo/female/gen/jump.ogg'
			if("laugh")
				used = list('sound/vo/female/gen/laugh (1).ogg','sound/vo/female/gen/laugh (2).ogg','sound/vo/female/gen/laugh (3).ogg')
			if("pleased")
				used = list('sound/vo/female/gen/pleased (1).ogg', 'sound/vo/female/gen/pleased (2).ogg', 'sound/vo/female/gen/pleased (3).ogg')
			if("pain")
				used = list('sound/vo/female/gen/pain (1).ogg','sound/vo/female/gen/pain (2).ogg','sound/vo/female/gen/pain (3).ogg')
			if("paincrit")
				used = list('sound/vo/female/gen/paincrit (1).ogg','sound/vo/female/gen/paincrit (2).ogg','sound/vo/female/gen/paincrit (3).ogg')
			if("painmoan")
				used = list('sound/vo/female/gen/painmoan (1).ogg','sound/vo/female/gen/painmoan (2).ogg','sound/vo/female/gen/painmoan (3).ogg','sound/vo/female/gen/painmoan (4).ogg','sound/vo/female/gen/painmoan (5).ogg','sound/vo/female/gen/painmoan (6).ogg','sound/vo/female/gen/painmoan (7).ogg','sound/vo/female/gen/painmoan (8).ogg')
			if("painscream")
				used = list('sound/vo/female/gen/painscream (1).ogg','sound/vo/female/gen/painscream (2).ogg','sound/vo/female/gen/painscream (3).ogg','sound/vo/female/gen/painscream (4).ogg','sound/vo/female/gen/painscream (5).ogg','sound/vo/female/gen/painscream (6).ogg','sound/vo/female/gen/painscream (7).ogg','sound/vo/female/gen/painscream (8).ogg')
			if("rage")
				used = list('sound/vo/female/gen/rage (1).ogg','sound/vo/female/gen/rage (2).ogg','sound/vo/female/gen/rage (3).ogg')
			if("scream")
				used = list('sound/vo/female/gen/scream (1).ogg','sound/vo/female/gen/scream (2).ogg','sound/vo/female/gen/scream (3).ogg','sound/vo/female/gen/scream (4).ogg')
			if("shh")
				used = list('sound/vo/female/gen/shh.ogg','sound/vo/female/gen/shh (2).ogg')
			if("sigh")
				used = list('sound/vo/female/gen/sigh (1).ogg','sound/vo/female/gen/sigh (2).ogg','sound/vo/female/gen/sigh (3).ogg')
			if("snore")
				used = list('sound/vo/female/gen/snore (1).ogg','sound/vo/female/gen/snore (2).ogg','sound/vo/female/gen/snore (3).ogg')
			if ("warcry")
				used = list('sound/vo/female/gen/warcry_female1.ogg','sound/vo/female/gen/warcry_female2.ogg','sound/vo/female/gen/warcry_female3.ogg')
			if("whimper")
				used = list('sound/vo/female/gen/whimper (1).ogg','sound/vo/female/gen/whimper (2).ogg','sound/vo/female/gen/whimper (3).ogg')
			if("whistle")
				used = list('sound/vo/female/gen/whistle (1).ogg','sound/vo/female/gen/whistle (2).ogg','sound/vo/female/gen/whistle (3).ogg','sound/vo/female/gen/whistle (4).ogg','sound/vo/female/gen/whistle (5).ogg')
			if("yawn")
				used = list('sound/vo/female/gen/yawn (1).ogg','sound/vo/female/gen/yawn (2).ogg','sound/vo/female/gen/yawn (3).ogg')
			if("attnwhistle")
				used = 'sound/vo/attn.ogg'
			if("psst")
				used = 'sound/vo/psst.ogg'
			if("clap")
				used = list('sound/vo/clap (1).ogg','sound/vo/clap (2).ogg','sound/vo/clap (3).ogg','sound/vo/clap (4).ogg')
			if("slowclap")
				used = list('sound/vo/slowclap.ogg')
			if("clap1")
				used = list('sound/vo/claponce.ogg')
			if("sexmoanlight")
				used = list('sound/vo/female/gen/se/sexlight (1).ogg','sound/vo/female/gen/se/sexlight (2).ogg','sound/vo/female/gen/se/sexlight (3).ogg','sound/vo/female/gen/se/sexlight (4).ogg','sound/vo/female/gen/se/sexlight (5).ogg','sound/vo/female/gen/se/sexlight (6).ogg','sound/vo/female/gen/se/sexlight (7).ogg')
			if("sexmoanhvy")
				used = list('sound/vo/female/gen/se/sex (1).ogg','sound/vo/female/gen/se/sex (2).ogg','sound/vo/female/gen/se/sex (3).ogg','sound/vo/female/gen/se/sex (4).ogg','sound/vo/female/gen/se/sex (5).ogg','sound/vo/female/gen/se/sex (6).ogg','sound/vo/female/gen/se/sex (7).ogg','sound/vo/female/gen/se/sex (8).ogg')
			if("meow")
				used = list('sound/vo/mobs/cat/cat_meow1.ogg', 'sound/vo/mobs/cat/cat_meow2.ogg', 'sound/vo/mobs/cat/cat_meow3.ogg', 'sound/vo/mobs/cat/cat_meow4.ogg')
			if("mrrp")
				used = list('sound/vo/mobs/cat/mrrp.ogg')
			if("caw")
				used = list('sound/vo/mobs/bird/CROW_01.ogg', 'sound/vo/mobs/bird/CROW_03.ogg',)
			if("peep")
				used = list('sound/vo/mobs/bird/peep.ogg')
			if("hiss")
				used = list('sound/vo/mobs/snake/hiss.ogg')
			if("phiss")
				used = list('sound/vo/mobs/possum/phiss.ogg')
			if("squeak")
				used = list('sound/vo/mobs/mouse/squeak.ogg')
			if("hoot")
				used = list('sound/vo/mobs/bird/hoot.ogg')
			if("snap")
				used = list('sound/vo/fsnap1.ogg')
			if("snap2")
				used = list('sound/vo/fsnap2.ogg')
			if("snap3")
				used = list('sound/vo/fsnap3.ogg')
			if("stomp")
				used = list('sound/foley/brickdrop.ogg')
			if("blink")
				used = list('sound/vo/blink.ogg')
			if("cackle")
				used = list('sound/vo/female/haughty/cackle (2).ogg')
			if("whine")
				used = list('sound/vo/mobs/vw/whine.ogg')
			if("fwhine")
				used = list('sound/vo/mobs/venard/fox1.ogg','sound/vo/mobs/venard/fox2.ogg','sound/vo/mobs/venard/fox3.ogg','sound/vo/mobs/venard/fox4.ogg','sound/vo/mobs/venard/fox5.ogg','sound/vo/mobs/venard/fox6.ogg','sound/vo/mobs/venard/fox7.ogg','sound/vo/mobs/venard/fox8.ogg','sound/vo/mobs/venard/fox9.ogg','sound/vo/mobs/venard/fox10.ogg','sound/vo/mobs/venard/fox11.ogg','sound/vo/mobs/venard/fox12.ogg','sound/vo/mobs/venard/fox13.ogg')
			if("psnort")
				used = list('sound/vo/mobs/dog/pugsnort.ogg')
			if("roar")
				used = list('sound/vo/mobs/cat/roar1.ogg', 'sound/vo/mobs/cat/roar2.ogg', 'sound/vo/mobs/cat/roar3.ogg', 'sound/vo/mobs/cat/roar4.ogg')
			if("howl")
				used = list('sound/vo/mobs/wwolf/ehowl1.ogg', 'sound/vo/mobs/wwolf/ehowl2.ogg', 'sound/vo/mobs/wwolf/ehowl3.ogg', 'sound/vo/mobs/wwolf/ehowl4.ogg', 'sound/vo/mobs/wwolf/ehowl5.ogg')
			if("prbt")
				used = list('sound/vo/mobs/shark/prbt.ogg')
			if("trill")
				used = list('sound/vo/mobs/cat/trill.ogg')
			if("purr")
				used = list('sound/vo/mobs/cat/cat_purr1.ogg', 'sound/vo/mobs/cat/cat_purr2.ogg', 'sound/vo/mobs/cat/cat_purr3.ogg', 'sound/vo/mobs/cat/cat_purr4.ogg')
			if("moo")
				used = list('sound/vo/mobs/minotaur/minoidle.ogg', 'sound/vo/mobs/minotaur/minoidle2.ogg', 'sound/vo/mobs/minotaur/minoidle3.ogg')
			if("bark")
				used = list('sound/vo/mobs/vw/bark (1).ogg', 'sound/vo/mobs/vw/bark (2).ogg', 'sound/vo/mobs/vw/bark (3).ogg', 'sound/vo/mobs/vw/bark (4).ogg', 'sound/vo/mobs/vw/bark (5).ogg', 'sound/vo/mobs/vw/bark (6).ogg', 'sound/vo/mobs/vw/bark (7).ogg')
			if("growl")
				used = list('sound/vo/mobs/vw/idle (1).ogg', 'sound/vo/mobs/vw/idle (2).ogg', 'sound/vo/mobs/vw/idle (3).ogg', 'sound/vo/mobs/vw/idle (4).ogg')
			if("bleat")
				used = list('sound/vo/mobs/goat/idle (1).ogg', 'sound/vo/mobs/goat/idle (2).ogg', 'sound/vo/mobs/goat/idle (3).ogg')
			if("chitter")
				used = 'sound/vo/moth/mothchitter.ogg'
			if("flutter")
				used = 'sound/vo/moth/moth_flutter.ogg'
			if("strain")
				used = 'sound/vo/female/gen/strain.ogg'
			if("yip")
				used = list('sound/vo/yip.ogg', 'sound/vo/yip2.ogg', 'sound/vo/yip3.ogg')
			if("oink")
				used = list('modular/Creechers/sound/pig1.ogg', 'modular/Creechers/sound/pig2.ogg')
			if("bellow")
				used = list('sound/vo/LizardBellow.ogg')
			if("hiss")
				used = list('sound/vo/LizardHiss.ogg')
			if("squeal")
				used = list('sound/vo/LizardSqueal.ogg')
			if("thump")
				used = list('sound/vo/LizardThump.ogg')
	return used
