GLOBAL_LIST_INIT(fracture_bclasses, list(
	BCLASS_BLUNT,
	BCLASS_SMASH,
	BCLASS_CHOP,
	BCLASS_PUNCH,
))

GLOBAL_LIST_INIT(artery_bclasses, list(
	BCLASS_CUT,
	BCLASS_CHOP,
	BCLASS_STAB,
	BCLASS_PICK,
	BCLASS_BITE,
	BCLASS_PIERCE,
))

GLOBAL_LIST_INIT(artery_strong_bclasses, list(
	BCLASS_CHOP,
	BCLASS_PICK,
))

GLOBAL_LIST_INIT(artery_heart_bclasses, list(
	BCLASS_PICK,
	BCLASS_PIERCE,
))

GLOBAL_LIST_INIT(dislocation_bclasses, list(
	BCLASS_TWIST,
))

GLOBAL_LIST_INIT(cbt_classes, list(
	BCLASS_BLUNT,
	BCLASS_SMASH,
	BCLASS_CHOP,
	BCLASS_PUNCH,
))

GLOBAL_LIST_INIT(stab_bclasses, list(
	BCLASS_STAB,
	BCLASS_PICK,
	BCLASS_PIERCE,
))

GLOBAL_LIST_INIT(whipping_bclasses, list(
	BCLASS_LASHING,
))

GLOBAL_LIST_INIT(sunder_bclasses, list(
	BCLASS_SUNDER,
))
