#define AUTO_IMPORT_ESSENTIALS list(\
	TRADE_GOOD_COAL,\
	TRADE_GOOD_WOOD,\
	TRADE_GOOD_GRAIN,\
	TRADE_GOOD_IRON_ORE,\
	TRADE_GOOD_HIDE,\
	TRADE_GOOD_FUR,\
	TRADE_GOOD_FAT\
)

#define AUTO_IMPORT_FLOOR 10
#define AUTO_IMPORT_BATCH 5
#define AUTO_IMPORT_MAX_PRICE_MULT 2
#define AUTO_IMPORT_PURSE_FLOOR_DEFAULT 1000
#define AUTO_IMPORT_HISTORY_DAYS 7
