#define FELLOWSHIP_MAX_MEMBERS 6
#define FELLOWSHIP_INVITE_EXPIRY (5 MINUTES)
#define FELLOWSHIP_NAME_MIN_LEN 3
#define FELLOWSHIP_NAME_MAX_LEN 32
#define FELLOWSHIP_FACTION_PREFIX "fellowship_"

#define FELLOWSHIP_REASON_LEFT "left"
#define FELLOWSHIP_REASON_KICKED "kicked"
#define FELLOWSHIP_REASON_DESTROYED "destroyed"
