// Global list for all learnable spells.
// Maybe one day we'll have different schools of spells etc. and a system tied to them but this is fine for now.

GLOBAL_LIST_INIT(learnable_spells, (list(/obj/effect/proc_holder/spell/invoked/projectile/fireball,
		/obj/effect/proc_holder/spell/invoked/projectile/lightningbolt,
		/obj/effect/proc_holder/spell/invoked/projectile/fetch,
		/obj/effect/proc_holder/spell/invoked/projectile/spitfire,
		/obj/effect/proc_holder/spell/invoked/forcewall,
		/obj/effect/proc_holder/spell/invoked/ensnare,
		/obj/effect/proc_holder/spell/self/message,
		/obj/effect/proc_holder/spell/invoked/repulse,
		/obj/effect/proc_holder/spell/invoked/blade_burst,
		/obj/effect/proc_holder/spell/targeted/touch/nondetection,
//  	/obj/effect/proc_holder/spell/invoked/knock,
		/obj/effect/proc_holder/spell/invoked/haste,
		/obj/effect/proc_holder/spell/invoked/featherfall,
		/obj/effect/proc_holder/spell/invoked/darkvision,
		/obj/effect/proc_holder/spell/invoked/longstrider,
		/obj/effect/proc_holder/spell/invoked/invisibility,
		/obj/effect/proc_holder/spell/invoked/projectile/acidsplash,
		/obj/effect/proc_holder/spell/invoked/projectile/fireball/greater,
//		/obj/effect/proc_holder/spell/invoked/frostbite,
		/obj/effect/proc_holder/spell/invoked/guidance,
		/obj/effect/proc_holder/spell/invoked/fortitude,
		/obj/effect/proc_holder/spell/invoked/snap_freeze,
		/obj/effect/proc_holder/spell/invoked/projectile/frostbolt,
		/obj/effect/proc_holder/spell/invoked/projectile/arcynebolt,
		/obj/effect/proc_holder/spell/invoked/projectile/arcynestrike,
		/obj/effect/proc_holder/spell/invoked/gravity,
		/obj/effect/proc_holder/spell/invoked/projectile/repel,

		/obj/effect/proc_holder/spell/targeted/touch/lesserknock,
		/obj/effect/proc_holder/spell/invoked/counterspell,
		/obj/effect/proc_holder/spell/invoked/enlarge,
		/obj/effect/proc_holder/spell/invoked/leap,
		/obj/effect/proc_holder/spell/invoked/blink,
		/obj/effect/proc_holder/spell/invoked/mirror_transform,
		/obj/effect/proc_holder/spell/invoked/mindlink,
		/obj/effect/proc_holder/spell/invoked/stoneskin,
		/obj/effect/proc_holder/spell/invoked/hawks_eyes,
		/obj/effect/proc_holder/spell/invoked/giants_strength,
		/obj/effect/proc_holder/spell/invoked/create_campfire,
		/obj/effect/proc_holder/spell/invoked/mending,
		/obj/effect/proc_holder/spell/self/light,
		/obj/effect/proc_holder/spell/invoked/conjure_weapon,
		/obj/effect/proc_holder/spell/self/conjure_armor,
		/obj/effect/proc_holder/spell/self/conjure_armor/dragonhide,
		/obj/effect/proc_holder/spell/self/magicians_brick,
		/obj/effect/proc_holder/spell/invoked/fire_cascade,
		/obj/effect/proc_holder/spell/invoked/firewalker,
		/obj/effect/proc_holder/spell/invoked/thunderstrike,
		/obj/effect/proc_holder/spell/invoked/sundering_lightning,
		/obj/effect/proc_holder/spell/invoked/meteor_storm,
		/obj/effect/proc_holder/spell/invoked/enchant_weapon,
		/obj/effect/proc_holder/spell/invoked/forcewall/arcyne_prison,
		/obj/effect/proc_holder/spell/invoked/forcewall/greater,
		/obj/effect/proc_holder/spell/invoked/wither,
		/obj/effect/proc_holder/spell/invoked/rebuke,
		/obj/effect/proc_holder/spell/invoked/projectile/fireball/artillery,
		/obj/effect/proc_holder/spell/invoked/conjure_primordial,
		/obj/effect/proc_holder/spell/invoked/raise_deadite,
		/obj/effect/proc_holder/spell/invoked/bonechill,
		/obj/effect/proc_holder/spell/invoked/silence,
		/obj/effect/proc_holder/spell/self/findfamiliar,
		/obj/effect/proc_holder/spell/invoked/projectile/stygian
		)
))
