// ----- ENGINE CONSTANTS -----

#define PRICING_ENGINE_DEFAULT_MARKUP 1.2
#define PRICING_ENGINE_COMMISSIONER_MARKUP 1
// Make it 0 or else we are in exploit city
#define PRICING_ENGINE_MIN_DERIVED_PRICE 0
#define PRICING_ENGINE_FOOD_RECIPE_MAX_PASSES 6


#define COMMISSIONER_CURED_LEATHER_PRICE 10

// Toggle on CSV dump for pricing engine audit. Use this to help find out the reasons for odd auto pricing.
// #define PRICING_ENGINE_DUMP_AUDITS

#define LOOTED_SELL_MULT ITEM_QUALITY_MULT_LOOTED

#define MARKUP_ARMOR_HELMETS 1.5
#define MARKUP_ARMOR_CHESTPIECES 1.5
#define MARKUP_ARMOR_LEGS 1.5
#define MARKUP_ARMOR_NECK 1.5
#define MARKUP_ARMOR_BOOTS 1.5
#define MARKUP_ARMOR_GLOVES 1.5
#define MARKUP_ARMOR_MASKS 1.5
#define MARKUP_ARMOR_BRACERS 1.5
#define MARKUP_ARMOR_BELTS 1.5
#define MARKUP_ARMOR_BARDING 1.5
#define MARKUP_ARMOR_LIGHT 2.0 // Slightly higher than metallic armor so tailor can make some decent money

#define MARKUP_WEAPONS_SWORDS 1.5
#define MARKUP_WEAPONS_DAGGERS 1.5
#define MARKUP_WEAPONS_AXES 1.5
#define MARKUP_WEAPONS_POLEARMS 1.5
#define MARKUP_WEAPONS_MACES 1.5
#define MARKUP_WEAPONS_FLAILS 1.5
#define MARKUP_WEAPONS_SHIELDS 1.5
#define MARKUP_WEAPONS_AMMO 1.5

#define MARKUP_TOOLS_COOKWARE 1.5
#define MARKUP_TOOLS_FIELD 1.5
#define MARKUP_TOOLS_WORKSHOP 1.5
#define MARKUP_TOOLS_SUNDRIES 1.5
#define MARKUP_TOOLS_ROGUE 1.5

#define MARKUP_VALUABLES_RINGS 1.5
#define MARKUP_VALUABLES_HOLY 1.5

#define MARKUP_DECORATION 1.5
#define MARKUP_POTTERY 1.5
#define GLAZE_BONUS_PCT 50
#define MARKUP_COMPONENTS 1.5
#define MARKUP_SMITHING_MISC 1.5

#define MARKUP_ENG_MACHINERY 1.5
#define MARKUP_ENG_CONSTRUCTION 1.5
#define MARKUP_ENG_COMBAT 1.5
#define MARKUP_ENG_TRIGGERS 1.5
#define MARKUP_ENG_MISC 1.5

#define MARKUP_GARMENT_COMMON 2.5
#define MARKUP_GARMENT_FINE 3.5

#define MARKUP_FOODSTUFF_FRESH 1.5
#define MARKUP_FOODSTUFF_PRESERVED 1.7

#define MARKUP_POTION 1.8

#define MARKUP_BOOK_WRIT 1.7
#define MARKUP_INSTRUMENT 1.7

#define MARKUP_TROPHY 2.0

#define MARKUP_RAW_MATERIAL_MINERAL 1.0
#define MARKUP_RAW_MATERIAL_ORGANIC 1.0
#define MARKUP_REAGENT_ALCHEMICAL 1.0
#define MARKUP_REAGENT_ARCANE 1.0
#define MARKUP_ARCYNE_GEARS 1.0
#define MARKUP_SALVAGE 1.0
#define MARKUP_LIVESTOCK 1.0
#define MARKUP_MISCELLANEOUS 1.0

#define INGOT_BRONZE_FROM_COPPER 1.0
#define INGOT_BRONZE_FROM_TIN 0.5
#define INGOT_SILVERBLESSED_MULT 1.1
#define INGOT_STEELHOLY_MULT 1.1
#define INGOT_BLACKSTEEL_FROM_STEEL 3
#define INGOT_BLACKSTEEL_FROM_SILVER 1
#define INGOT_LITHMYC_MULT 12.0
#define INGOT_PURIFIEDAALLOY_MULT 1.0
#define INGOT_AALLOY_MULT 0.25
#define INGOT_DROW_MULT 1.0

#define MATERIAL_PLANK_FROM_WOOD 1.5
#define MATERIAL_ROGUEGEAR_FROM_STEEL 1.0

// ----- ATC WAREHOUSE MARKET POOLS -----
// Pool capacity in mammon per category. Capacity scales sublinearly with player population.
#define MARKET_POOL_TIER_LOOT 1000
#define MARKET_POOL_TIER_MID 500
#define MARKET_POOL_TIER_STANDARD 250

#define NAVIGATOR_BUCKET_WEAPONS "Weapons"
#define NAVIGATOR_BUCKET_ARMOR_LIGHT "Light Armor"
#define NAVIGATOR_BUCKET_ARMOR_HEAVY "Heavy Armor"
#define NAVIGATOR_BUCKET_GARMENT_COMMON "Common Garments"
#define NAVIGATOR_BUCKET_GARMENT_FINELUX "Fine Garments"
#define NAVIGATOR_BUCKET_ENGINEERING "Engineering"
#define NAVIGATOR_BUCKET_VALUABLES_CRAFTED "Crafted Valuables"
#define NAVIGATOR_BUCKET_VALUABLES_LOOTED "Looted Valuables"
#define NAVIGATOR_BUCKET_CARVED "Carved Goods"
#define NAVIGATOR_BUCKET_POTTERY "Pottery & Ceramics"
#define NAVIGATOR_BUCKET_TROPHIES "Trophies"
#define NAVIGATOR_BUCKET_ENCHANTMENTS "Enchantment Scrolls"
#define NAVIGATOR_BUCKET_INSTRUMENTS "Instruments"
#define NAVIGATOR_BUCKET_SEAFOOD "Seafood"
#define NAVIGATOR_BUCKET_POTIONS_REAGENTS "Potions & Reagents"
#define NAVIGATOR_BUCKET_MISCELLANEOUS "Miscellaneous"

#define NAVIGATOR_BUCKET_REFUSED_FOOD "refused_food"
#define NAVIGATOR_BUCKET_REFUSED_BULK "refused_bulk"

#define NAVIGATOR_BUCKET_POOL_WEAPONS 500
#define NAVIGATOR_BUCKET_POOL_ARMOR_LIGHT 200
#define NAVIGATOR_BUCKET_POOL_ARMOR_HEAVY 400
#define NAVIGATOR_BUCKET_POOL_GARMENT_COMMON 400
#define NAVIGATOR_BUCKET_POOL_GARMENT_FINELUX 600
#define NAVIGATOR_BUCKET_POOL_ENGINEERING 300
#define NAVIGATOR_BUCKET_POOL_VALUABLES_CRAFTED 800
#define NAVIGATOR_BUCKET_POOL_VALUABLES_LOOTED 1400
#define NAVIGATOR_BUCKET_POOL_CARVED 400
#define NAVIGATOR_BUCKET_POOL_POTTERY 300
#define NAVIGATOR_BUCKET_POOL_TROPHIES 800
#define NAVIGATOR_BUCKET_POOL_ENCHANTMENTS 400
#define NAVIGATOR_BUCKET_POOL_INSTRUMENTS 200
#define NAVIGATOR_BUCKET_POOL_SEAFOOD 500
#define NAVIGATOR_BUCKET_POOL_POTIONS_REAGENTS 800
#define NAVIGATOR_BUCKET_POOL_MISCELLANEOUS 300

#define NAVIGATOR_REFUSAL_MSG_FOOD "The market does not accept foodstuffs - sell to docked ships' victuallers."
#define NAVIGATOR_REFUSAL_MSG_BULK "Bulk goods are not handled at the balloon - sell to docked ships."

#define MARKET_POOL_JITTER_LOW 0.7
#define MARKET_POOL_JITTER_HIGH 1.3

#define MARKET_POOL_POP_REFERENCE 15 // Base number before scaling starts
#define MARKET_POOL_POP_SCALE 0.005 // I set this to be 0.5% per player, which means that
// for lowpop server / crafter heavy server there's generous pools, whereas highpop
// must relies on merchant active management

// Per-bucket scale overrides. Looted Valuables scales faster (0.75%/player) so highpop has more headroom before complaints
#define MARKET_POOL_POP_SCALE_VALUABLES_LOOTED 0.0075

#define MARKET_POOL_RESNAPSHOT_INTERVAL (15 MINUTES)

#define MARKET_DEMAND_PER_SHIP_FRACTION 0.5
#define MARKET_DEMAND_MAX_POOL_MULT 2.0
#define MARKET_DEMAND_PAYOUT_MAX_MULT 1.5
#define MARKET_DEMAND_SHIP_SATURATION_DRAIN 0.50
#define MARKET_DEMAND_NO_SHIP_FLOOR 0.5

#define MARKET_THEME_WARGEAR "wargear"
#define MARKET_THEME_ARCYNE "arcyne"
#define MARKET_THEME_GARMENTS "garments"
#define MARKET_THEME_FOODSTUFFS "foodstuffs"
#define MARKET_THEME_LOOT "loot"
#define MARKET_THEME_RAWS "raws"
#define MARKET_THEME_ENGINEERING "engineering"
#define MARKET_THEME_MISC "misc"

#define MARKET_THEME_HIGH_JITTER 1.15
#define MARKET_THEME_LOW_JITTER 0.85

// Smuggler Navigator pool. Half the size of Real, no demand layer, saturation regenerates daily.
#define MARKET_BM_POOL_FRACTION 0.5
#define MARKET_BM_DAILY_SATURATION_REGEN 0.25

// ----- ALCHEMICAL INGREDIENT PRICING -----
#define SELLPRICE_HERB_COMMON 4
#define SELLPRICE_HERB_UNCOMMON 6
#define SELLPRICE_HERB_RARE 10
#define SELLPRICE_BONE 3
#define SELLPRICE_SINEW 2
#define SELLPRICE_HORN 8
#define SELLPRICE_DUST_FROM_INGOT_MULT 0.25
#define SELLPRICE_ARCANE_DUST_LOW 4
#define SELLPRICE_ARCANE_DUST_MID 6
#define SELLPRICE_ARCANE_DUST_HIGH 8
