/datum/asset/simple/roguefonts
	keep_local_name = TRUE
	assets = list(
		"pterra.ttf" = 'interface/fonts/pterra.ttf',
		"chiseld.ttf" = 'interface/fonts/chiseld.ttf',
		"blackmoor.ttf" = 'interface/fonts/blackmoor.ttf',
		"handwrite.ttf" = 'interface/fonts/handwrite.ttf',
		"book1.ttf" = 'interface/fonts/book1.ttf',
		"book2.ttf" = 'interface/fonts/book1.ttf',
		"book3.ttf" = 'interface/fonts/book1.ttf',
		"book4.ttf" = 'interface/fonts/book1.ttf',
		"dwarf.ttf" = 'interface/fonts/languages/dwarf.ttf',
		"elf.ttf" = 'interface/fonts/languages/elf.ttf',
		"hell.ttf" = 'interface/fonts/languages/hell.ttf',
		"orc.ttf" = 'interface/fonts/languages/orc.ttf',
		"sand.ttf" = 'interface/fonts/languages/sand.ttf',
		"undead.ttf" = 'interface/fonts/languages/undead.ttf',
		"draconic.ttf" = 'interface/fonts/languages/draconic.ttf',
		"grenzelhoftian.ttf" = 'interface/fonts/languages/grenzelhoftian.ttf',
		"kazengunese.ttf" = 'interface/fonts/languages/kazengunese.ttf',
		"lingyuese.ttf" = 'interface/fonts/languages/lingyuese.ttf',
		"otavan.ttf" = 'interface/fonts/languages/otavan.ttf',
		"oldazure.ttf" = 'interface/fonts/languages/oldazure.ttf',
		"etruscan.ttf" = 'interface/fonts/languages/etruscan.ttf',
		"gronnic.ttf" = 'interface/fonts/languages/gronnic.ttf',
		"aavnic.ttf" = 'interface/fonts/languages/aavnic.ttf',
	)
